mpc_node:
  ros__parameters:
    dT: 0.175
    mpc_steps_N: 30
    vehicle_L: 1.53
    max_speed: 10.0
    mpc_ref_cte: 0.0
    mpc_ref_epsi: 0.0
    mpc_ref_vel: 10.0

    mpc_w_cte: 100.0
    mpc_w_lag: 700.0
    mpc_w_vel: 1.5
    mpc_w_p: 45.0
    mpc_w_delta: 41.0
    mpc_w_accel: 50.0
    mpc_w_delta_d: 1500.0
    mpc_w_delta_p: 0.0

    mpc_max_steering: 0.6
    mpc_max_throttle: 1.0
    mpc_bound_value: 1000.0

    p_max: 11.0
    d_v_bound: 2.0
    d_theta_bound: 0.5
    d_p_bound: 2.0

    debug_mode: true
    delay_mode: true
    car_width: 1.3
    spline_poly_order: 3
    goal_threshold: 0.6
    controller_freq: 20
    path_folder_name: fssim
    inflation_factor: 0.6
    lag_time: 0.05
    ipopt_verbose: true
    car_frame: fssim/vehicle/base_link

    odom_topic_name: /ego_racecar/odom
    goal_topic_name: /move_base_simple/goal
    cmd_vel_topic_name: /vesc/high_level/ackermann_cmd_mux/input/nav_0
    localized_pose_topic_name: /pf/viz/inferred_pose
